### ISSUE TITLE
针对 HTML 中的 script 和 style 标签内容作检查

### ISSUE THREAD

**Issue by chriswong** [ecomfe/htmlcs#24]
碰到 inline 的 script 和 style 内容，提供注入点，调用外部的 js/css linter 来检查，注入的方法期望以参数形式得到文件路径与文本内容，返回的是 message 数组。

对于 message 对应行数的校正，需要加上 script 标签所在的行数，这个可以在 fecs 做，也可以在 htmlcs 做。

还有一种 hack 方式的做法是根据 script 的行数在 content 前补 \n 实现，最后才考虑。

**Comment by nighca** [comment]
https://github.com/ecomfe/htmlcs/pull/30
