### ISSUE TITLE
自定义rule不起作用

### ISSUE THREAD

**Issue by vicerwang** [ecomfe/htmlcs#40]
如下使用，自定义的rule不起作用：
```javascript
var htmlcs = require("htmlcs");
var formMethodRule = require("./rules/form-method");
htmlcs.addRule(formMethodRule);
var result = htmlcs.hintFile("./test.html");
console.log(result);
```
看了下源码，在htmlcs.hint方法中调用了rules.js的init方法，init方法重新初始化了rules数组，导致之前通过addRule方法添加的自定义rule被覆盖掉，注释掉这段代码就起作用了。
不知道是不是我用的不对，readme中也没有添加自定义rule相关的说明。

**Comment by nighca** [comment]
嗯，是有问题，有一次改 lint 的机制，把 init 放进来做，引入了问题一直没发现，我改下

**Comment by nighca** [comment]
已修复，addRule 的使用可先参考 https://github.com/ecomfe/htmlcs/blob/master/test/lib/htmlcs.spec.js#L35
后续我补一下文档。
