### ISSUE TITLE
Support for custom path of the config file

### ISSUE THREAD

**Issue by selevit** [ecomfe/htmlcs#43]
It would be nice if this linter could  get path for the custom config file from command line argument.

For example:

```sh
htmlcs --config=/path/to/.htmlcsrc
```

P. S. Thank you for great tool!

**Comment by nighca** [comment]
Thanks for your suggestion, I'll take it into consideration in future development.

The CLI tool is far from good enough, as it's not the key part of htmlcs now (I'm working on some exciting features/rules). if the current CLI tool can not meet your need, I'll recommend to `require` htmlcs and call its methods in your own code, which is more flexible.

Also, your pr will be very welcomed!

**Comment by selevit** [comment]
Thank's for your reply!

I'm using this tool from python script. So direct calling of NodeJS code is not very cosily in this situation.

**Comment by nighca** [comment]
https://github.com/ecomfe/htmlcs/pull/47

**Comment by nighca** [comment]
@selevit https://github.com/ecomfe/htmlcs#usage
