### ISSUE TITLE
可否支持 YAML 格式的配置文件

### ISSUE THREAD

**Issue by sodatea** [ecomfe/htmlcs#52]
1. 个人比较喜欢在配置文件里加注释，这样就不用单独出一份项目的规范文档，直接看配置文件就够了；
2. [YAML 是 JSON 的超集](https://en.wikipedia.org/wiki/YAML#JSON)，所以这不会带来任何兼容性问题；
3. 目前配置信息是用 manis + strip-json-comments 载入的，虽然支持了在 JSON 里加注释，但是毕竟带注释就不符合 JSON 规范了，还是改用 YAML 比较自然；
4. manis 的示例里也有[载入 YAML 格式配置文件的例子](https://github.com/ecomfe/manis#user-content-loading-yml-with-js-yaml)，这个功能加起来应该很容易。

**Comment by nighca** [comment]
谢谢建议，最近考虑支持
