### ISSUE TITLE
Rule for '<!doctype html>' rather than '<!DOCTYPE html>'

### ISSUE THREAD

**Issue by jamesspittal** [ecomfe/htmlcs#57]
Is there a way in `htmlcs` to warn on:

``` html
<!doctype html>
<html>
  <head>
    <!-- ... -->
  </head>
```

... which should ideally be:

``` html
<!DOCTYPE html>
<html>
  <head>
    <!-- ... -->
  </head>
</html>
```

Does a rule for this exist currently? (Apologies, I'm still new to `htmlcs`).

**Comment by jamesspittal** [comment]
After some further investigation, it appears that a rule does not exist for this currently, but I've taken a look at `lib/rules/doctype.js` and figure it should be pretty straight forward to create a new rule for `doctype-uppercase.js`.

I will submit a pull request once done (assuming you are accepting pull requests).

**Comment by nighca** [comment]
Of course pr is welcomed!

Howerver, I think it will be more proper to implement it in rule `doctype`, since the rule has already done some checking more than "DOCTYPE needed", such as "DOCTYPE must be html5". Maybe we can use a config option to specify if uppercase is required.

**Comment by jamesspittal** [comment]
Thanks @nighca - that's a good idea (implementing it in the rule `doctype`).

**Comment by jamesspittal** [comment]
Spent a little bit of time having a play and came up with this pull request - hope this helps.

I didn't get to address the suggestion you made (which I think is a great idea):

> Maybe we can use a config option to specify if uppercase is required.

**Comment by olegkrivtsov** [comment]
Hi @jamesspittal, I've modified the `doctype` rule, so now you can use the following in configuration:
```
"doctype": "upper",
```
and it will require that `<!DOCTYPE>` be used instead of `<!doctype>`.
Fixed in:  https://github.com/ecomfe/htmlcs/pull/90
With this, I've fixed all the bugs reported by you.

**Comment by jamesspittal** [comment]
Thanks @olegkrivtsov - great work.
