### ISSUE TITLE
New rule - Warn on HTML comments not in the following format

### ISSUE THREAD

**Issue by jamesspittal** [ecomfe/htmlcs#60]
Based on inspiration from this HTML coding standard:

![image](https://cloud.githubusercontent.com/assets/4592650/11858678/aa5f220e-a4b7-11e5-9eed-4b73892ffce0.png)

Source: https://github.com/xhtmlized/html-coding-standards#comments

It would be nice to have an optional rule-set to check for this.

**Comment by nighca** [comment]
That's not a necessary rule in my opinion.

However, you can pass your impelementation into htmlcs with `htmlcs.addRule` If you really need it. :)

**Comment by jamesspittal** [comment]
Fair point. I can see that it's a rather "customised" use case, so I'll take your suggestion as per:

> However, you can pass your impelementation into htmlcs with `htmlcs.addRule` so you can do such checking, if you really need it. :)

Thanks for the pointer + response. Closing.
