### ISSUE TITLE
New rule - Unnecessary usage of white-space

### ISSUE THREAD

**Issue by jamesspittal** [ecomfe/htmlcs#61]
I am looking for feedback on this as a new (optional) rule.

Specifically - the unnecessary usage of one or multiple unnecessary white-spaces before the closing of a tag.

Specifically. This rule-set would warn on examples such as:

``` html
<!-- Not recommended -->
<h3>PRIVACY POLICY </h3>
```

But not:

``` html
<!-- Recommended -->
<h3>PRIVACY POLICY</h3>
```

It would also apply to other tags, such as `<strong>`, i.e.:

``` html
<!-- Not recommended -->
<strong>Use of your personal information </strong>
```

But not:

``` html
<!-- Recommended -->
<strong>Use of your personal information</strong>
```

Feedback welcome.

**Comment by nighca** [comment]
Agree.

**Comment by olegkrivtsov** [comment]
Hi @jamesspittal, this has been implemented in https://github.com/ecomfe/htmlcs/pull/90

**Comment by jamesspittal** [comment]
Thanks @olegkrivtsov - great work.

**Comment by olegkrivtsov** [comment]
Probably this can be closed.
