### ISSUE TITLE
New rule - warning on multiple style sheets included where one will do

### ISSUE THREAD

**Issue by jamesspittal** [ecomfe/htmlcs#62]
Inspired in part by the concept of 'Seperation of Concerns' (with an example in the HTML/CSS context here: https://google.github.io/styleguide/htmlcssguide.xml#Separation_of_Concerns).

An optional rule-set that produces a warning on cases where more than one style-sheet is included, example:

``` html
    <link rel="stylesheet" href="assets/css/normalize.css">
    <link rel="stylesheet" href="assets/css/global.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/tablet.css">
    <link rel="stylesheet" href="assets/css/mobile.css">
    <link rel="stylesheet" href="assets/css/colorbox.css">
```

... whereas, combining all style-sheets into one neat CSS file would be cleaner and represent a better "separation of concerns". Example:

``` html
    <link rel="stylesheet" href="assets/css/default.css">
```

This concept has been debated quite a long time and it's somewhat controversial, examples:
- http://stackoverflow.com/questions/2336302/single-huge-css-file-vs-multiple-smaller-specific-css-files
- http://stackoverflow.com/questions/32041281/one-big-css-file-vs-multiple-small-css-files

However, if you do not agree with this coding standard, it can simply be not included in your coding standard rule-set (and possibly it should be not included in the default rule-set).

**Comment by nighca** [comment]
Agree.

**Comment by olegkrivtsov** [comment]
Hi @jamesspittal, this has been implemented in https://github.com/ecomfe/htmlcs/pull/90

**Comment by jamesspittal** [comment]
Thanks @olegkrivtsov
