### ISSUE TITLE
New rule - Use a new line for every block, list, or table element, and indent every such child element.

### ISSUE THREAD

**Issue by jamesspittal** [ecomfe/htmlcs#63]
Based on inspiration from https://google.github.io/styleguide/htmlcssguide.xml#General_Formatting

> **Use a new line for every block, list, or table element, and indent every such child element.**
> 
> Independent of the styling of an element (as CSS allows elements to assume a different role per display property), put every block, list, or table element on a new line.
> 
> Also, indent them if they are child elements of a block, list, or table element.
> 
> (If you run into issues around whitespace between list items it’s acceptable to put all li elements in one line. A linter is encouraged to throw a warning instead of an error.)
> 
> ``` html
> 
> <blockquote>
>   <p><em>Space</em>, the final frontier.</p>
> </blockquote>
> <ul>
>   <li>Moe
>   <li>Larry
>   <li>Curly
> </ul>
> <table>
>   <thead>
>     <tr>
>       <th scope="col">Income
>       <th scope="col">Taxes
>   <tbody>
>     <tr>
>       <td>$ 5.00
>       <td>$ 4.50
> </table>
> ```

An example that would produce a warning would be the following on one line:

``` html
<div class="work-details clearfix"> <img src="assets/images/location-icon.png" alt="Location"> </div>
```

... which would ideally be written (although strictly speaking `<img>` isn't a "block element") as:

``` html
<div class="work-details clearfix">
  <img src="assets/images/location-icon.png" alt="Location">
</div>
```

This would also warn on examples like:

``` html
<ul>
  <li>Line item 1</li><li>Line item 2</li>
  <li>Line item 3</li>
</ul>
```

... which would ideally be written as:

``` html
<ul>
  <li>Line item 1</li>
  <li>Line item 2</li>
  <li>Line item 3</li>
</ul>
```

**Comment by olegkrivtsov** [comment]
@jamesspittal I've added the `new-line-for-blocks` rule which checks if there is a new line before each block element. But, I'm not sure how to check if a block element is properly indented. For example, 2 space indentation is correct sometimes, while 4 space indentation is correct in other cases. How to resolve this elegantly?

**Comment by jamesspittal** [comment]
Hi @olegkrivtsov Good point. Maybe options for for `2-spaces`, `4-spaces` or `tab` (similar to Notepad++)?

**Comment by olegkrivtsov** [comment]
@jamesspittal, OK, will check how options are added in `htmlcs` project.

**Comment by olegkrivtsov** [comment]
Hi @jamesspittal I've done that the `new-line-for-blocks` rule additionally checks if the child block element has indent and that the indent is larger that its parent's indent. This works for all indent types: `space-2`, `space-4` and `tab`. However, this rule is better to be used with `tag-pair` rule, whuich ensures if a tag has closing tag.

**Comment by jamesspittal** [comment]
Thanks @olegkrivtsov

**Comment by olegkrivtsov** [comment]
Probably this needs to be closed.
