### ISSUE TITLE
New rule - Warn if protocol is not omitted from embedded resources ('http://' or 'https://' rather than '//')

### ISSUE THREAD

**Issue by jamesspittal** [ecomfe/htmlcs#64]
Incorrect example:

``` html
<link href="https://fonts.googleapis.com/css?family=Lato:400,300,700italic" rel="stylesheet">
```

This should ideally be:

``` html
<link href="//fonts.googleapis.com/css?family=Lato:400,300,700italic" rel="stylesheet">
```

Incorrect example:

``` html
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script> 
```

This should ideally be:

``` html
<script src="//code.jquery.com/jquery-1.9.1.min.js"></script> 
```

Google's HTML/CSS style guide has a similar thing: https://google.github.io/styleguide/htmlcssguide.xml?showone=Protocol#Protocol

In it, they explain:

> Omitting the protocol—which makes the URL relative—prevents mixed content issues and results in minor file size savings.
> 
> Omit the protocol portion (http:, https:) from URLs pointing to images and other media files, style sheets, and scripts unless the respective files are not available over both protocols.

**Comment by nighca** [comment]
Agree.

**Comment by olegkrivtsov** [comment]
Fixed in https://github.com/ecomfe/htmlcs/pull/90

**Comment by olegkrivtsov** [comment]
Probably this needs to be closed.
