### ISSUE TITLE
White-space before end of close tag does not trigger warning

### ISSUE THREAD

**Issue by jamesspittal** [ecomfe/htmlcs#65]
Interestingly, I discovered that the following:

``` html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
```

'validates' and does not trigger a 'warning'.

However, I would argue that it really should be:

``` html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```

Should there be a rule for this? Does this classify as a `bug` or a new rule-set (or perhaps neither)?

Feedback welcome.

**Comment by chriswong** [comment]
I think we need a new rule for it.

**Comment by nighca** [comment]
Agree.

**Comment by olegkrivtsov** [comment]
@jamesspittal Added the `no-space-before-tag-end` rule which validates that there is no space before tag end.

**Comment by nighca** [comment]
@olegkrivtsov Thanks for your work. I've commented the PR for a few suggestions.
@chriswong What do you think?
