### ISSUE TITLE
[NewRule] no-style-class

### ISSUE THREAD

**Issue by chriswong** [ecomfe/htmlcs#7]
[强制] `class` 必须代表相应模块或部件的内容或功能，不得以样式信息进行命名。

**Comment by nighca** [comment]
这个没思路啊，求指点

**Comment by Justineo** [comment]
这个我不觉得能用工具解决……

**Comment by nighca** [comment]
我以为也许是匹配一些特殊/典型样式名的方式，比如ml10这种，但是这么做很不严谨

**Comment by chriswong** [comment]
收集一些常见的原子类名，降低一下报错级别？

**Comment by Justineo** [comment]
我觉得这条还是放给人肉 codereview 的时候来做比较好，强行匹配不是很严谨吧。

**Comment by chriswong** [comment]
见 #84
