### ISSUE TITLE
When configuring indent-char to space-2 formatting still uses space-4

### ISSUE THREAD

**Issue by rahulsom** [ecomfe/htmlcs#76]
The checker is fine, but the formatter doesn't respect the setting.

**Comment by nighca** [comment]
Thanks for feedback.

`format` method for rule [indent-char](https://github.com/ecomfe/htmlcs/blob/master/lib/rules/indent-char.js) is not implemented yet, which means formatting always uses default indent option now. We'll put it on our schedule.

**Comment by nighca** [comment]
Done. @rahulsom

**Comment by rahulsom** [comment]
Thanks! This is awesome.
