### ISSUE TITLE
赞，不错~不过可惜我的atom编辑器没有插件支持~

### ISSUE THREAD

**Issue by yalishizhude** [ecomfe/htmlcs#81]
😟

**Comment by chriswong** [comment]
https://github.com/ecomfe/fecs/wiki/FAQ#%E6%9C%89%E6%B2%A1%E6%9C%89%E9%9B%86%E6%88%90%E5%88%B0%E7%BC%96%E8%BE%91%E5%99%A8%E6%88%96-ide-%E7%9A%84%E6%94%AF%E6%8C%81
