### ISSUE TITLE
protocol-omitted-in-href Rule - Do not warn on rel="canonical"

### ISSUE THREAD

**Issue by jamesspittal** [ecomfe/htmlcs#93]
I enabled the `protocol-omitted-in-href` rule and the following code-block triggered a warning:

````html
    <link rel="canonical" href="http://www.website.com.au/v2/">
````

In my opinion, this is OK. It does not need to be:

````html
    <link rel="canonical" href="//www.website.com.au/v2/">
````

So, `protocol-omitted-in-href` should probably skip `rel="canonical"` links. It did however warn on:

````html
    <link href="https://fonts.googleapis.com/css?family=Taviraj:300,400,400i,500,500i,700" rel="stylesheet">
````

... which is correct. This is better as:

````html
    <link href="//fonts.googleapis.com/css?family=Taviraj:300,400,400i,500,500i,700" rel="stylesheet">
````

**Comment by nighca** [comment]
@jamesspittal It makes sense.
However I wonder if there are any other types of tags, whose href should be treated specially like `<link rel="canonical" ...>`. 
If you have any hint:)

**Comment by jamesspittal** [comment]
Thanks @nighca - `rel="canonical"` is the only edge case that comes to mind right now, but I'll definitely keep you posted if we notice any others in our usage.

**Comment by jamesspittal** [comment]
@olegkrivtsov is going to submit a patch/pull request for this when he has some spare hours.

**Comment by nighca** [comment]
@jamesspittal That will be great!

**Comment by olegkrivtsov** [comment]
Hi @jamesspittal This has been fixed.

**Comment by jamesspittal** [comment]
Thanks @olegkrivtsov
